import type { Metadata } from "next";
import "./globals.css";
import { Ubuntu } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Analytics } from "@vercel/analytics/react"

const ubuntu = Ubuntu({
  weight : '400', 
  subsets : ["greek"]
});

export const metadata: Metadata = {
  title: "Robotika UMRAH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children, 
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <meta charSet={"UTF-8"} />
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  
      <body
        className={`${ubuntu.className} w-full antialiased bg-white `}
      >
        <Analytics/>
        <Navbar/>
        {children}
        <Footer/>

      </body>
    </html>
  );
}
